### PR TITLE
set the title if is an xterm

### PR DESCRIPTION
**Pull request by frank-bg**
this pr set title of xterm, probably is better to add a third argument (optional) for such setting 

Selection_167

### CODE REVIEW

**Comment by musm** [comment]
This should not be set like this and if it is implemented needs to be an option.

**Comment by frank-bg** [comment]
I'm sure it's not the right way of doing it, which option name can be? is there some standard to follow?

**Comment by frank-bg** [comment]
I already see bash.* is used

**Comment by musm** [comment]
Just add it as a first argument, e.g.

```
hostname=`echo $HOSTNAME`
TITLE="\033]0;${HOST}\007"
PROMPT_COMMAND='"${TITLE-}${PROMPT_DIR_COLOR}\w${RESTORE} " "\n${PROMPT_SYMBOL_COLOR}\$ ${PROMPT_RESTORE}";'

```

**Comment by frank-bg** [comment]
yeah! prepend to prefix does the trick

**Pull request closed without merging**
