### PR TITLE
Improve git-prompt.sh to reflect 'typechange's

### PR DESCRIPTION
**Pull request by PetrJarosik**
Reflect also 'typechange' modification on prompt.

### CODE REVIEW

**Comment by lyze** [comment]
Hi, thanks for your change! It looks good to me.

Would you mind adding a new testcase in `git-prompt-test.sh` and then running `make test` if you have the time? Thanks! Otherwise, I'll try to find some time later in the week to do that.

**Comment by PetrJarosik** [comment]
Hi, I am really busy and I have no time to create the test. So do that yourself please.

Thanks,
Petr

**Comment by PetrJarosik** [comment]
Hi, can you create the testcase & merge the pull request please?

**Comment by PetrJarosik** [comment]
I can see that you didn't use my change but created your own on commit  [0a236e8d68417f526412d2657e345e408fd49250](https://github.com/lyze/posh-git-sh/commit/0a236e8d68417f526412d2657e345e408fd49250).

OK, thank you for the correction.

**Pull request closed without merging**
