### PR TITLE
Added branch status symbols like new poshgit

### PR DESCRIPTION
**Pull request by moosekaka**
I added unicode symbols showing the branch status, like the recent versions of posh-git on PS. Unicode encoded as 3byte hex. Haven't tested if it works in zsh but it works in BASH.

### CODE REVIEW

**Comment by moosekaka** [comment]
closing as there is a bug when there are changes to the index

**Comment by lyze** [comment]
What exactly is the bug that caused you to close this pull request?

**Comment by moosekaka** [comment]
I'm not very sure it was a bug; the unicode symbols were not displaying properly when there were modified or untracked files, but I checked the code again and this time the bug doesn't appear. It's only a few lines of modifications so I'll reopen the pull request.

**Comment by moosekaka** [comment]
Closing and opening pull request from a new re-fork.

**Pull request closed without merging**
